meta:
  schema-version: 0.1.0
  created-on: "2024-02-15T11:42:41Z"
  cli-version: 0.2.0
projects:
  2lambda123-botkit-package-lock.json:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "7"
    overrides:
      decode-uri-component:
        0.2.0:
          use: 0.2.0-sp1
      semver:
        6.3.0:
          use: 6.3.0-sp1
        5.7.1:
          use: 5.7.1-sp1
        7.3.5:
          use: 7.3.5-sp1
      tough-cookie:
        2.5.0:
          use: 2.5.0-sp1
      lodash.template:
        4.5.0:
          use: 4.5.0-sp1
      qs:
        6.5.2:
          use: 6.5.2-sp1
      "@babel/traverse":
        7.17.3:
          use: 7.17.3-sp1
      http-cache-semantics:
        4.1.0:
          use: 4.1.0-sp1
      ip:
        1.1.5:
          use: 1.1.5-sp1
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      word-wrap:
        1.2.3:
          use: 1.2.3-sp1
      json5:
        2.2.0:
          use: 2.2.0-sp1
