meta:
  schema-version: 0.1.0
  created-on: "2024-02-15T11:42:38Z"
  cli-version: 0.2.0
projects:
  2lambda123-botkit-packages-botkit-plugin-cms-package-lock.json:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "7"
    overrides:
      word-wrap:
        1.2.3:
          use: 1.2.3-sp1
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
